name: Deploy Static Web App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: |
          docker build -t my-web-app .
      
      - name: Run Container Locally (Test)
        run: |
          docker run -d -p 8080:80 my-web-app
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Push to Docker Hub
        run: |
          docker tag my-web-app ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest
