name: Build & Deploy Web App

on: 
  push:
    branches:
      - main

jobs:
  build-deploy: 
    name: Build and Deploy Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      
      #Run tests
      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_ACCESS_TOKEN}}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: ${{secrets.DOCKER_USERNAME}}/simple-web-app:latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
            context: .
            dockerfile: Dockerfile
            push: true
            tags: ${{secrets.DOCKER_USERNAME}}/simple-web-app:latest